version: 2
jobs:
    build:
        working_directory: ~/react-design-patterns
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v3-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - ~/.cache
                      - node_modules
                  key: v3-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint
            - run:
                  name: Unit Tests
                  command: |
                      yarn test
            - run:
                  name: design pattern cypress tests
                  command: yarn cytest
            - store_artifacts:
                  path: cypress/screenshots
