version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
jobs:
    build_project:
        working_directory: ~/react-design-patterns
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v3-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - ~/.cache
                    - node_modules
                key: v3-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Prettier Check
                command: |
                    yarn prettier:check
            - run:
                name: Lint
                command: |
                    yarn lint
            - run:
                name: Unit Tests
                command: |
                    yarn test --coverage --watchAll=false
            - run:
                name: Build Project
                command: |
                    yarn build
            - persist_to_workspace:
                root: .
                paths:
                    - coverage

    cypress_tests:
        working_directory: ~/react-design-patterns
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v3-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - ~/.cache
                    - node_modules
                key: v3-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Cypress E2E Tests
                command: |
                    yarn cytest
            - store_artifacts:
                path: cypress/screenshots

    coverage_report:
        working_directory: ~/react-design-patterns
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/clover.xml'
                token: 74ebd8f2-0b51-4873-972a-82c2b3509b37

workflows:
    version: 2
    react_design_patterns:
        jobs:
            - build_project
            - cypress_tests:
                    requires:
                        - build_project
                    filters:
                        branches:
                            only:
                                - master
                                - dev
            - coverage_report:
                   requires:
                        - build_project
                #    filters:
                #         branches:
                #             only:
                #                 - master